# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5, unique=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('objetivo', models.TextField(blank=True, verbose_name='Obejtivo')),
                ('perfil_profissional', models.TextField(blank=True, verbose_name='Perfil Profissional')),
                ('mercado_trabalho', models.TextField(blank=True, verbose_name='Mercado de Trabalho')),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
    ]
