# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 03:32
from __future__ import unicode_literals

import contas.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ra', models.IntegerField(unique=True, verbose_name='RA')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=80)),
                ('password', models.TextField()),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('perfil', models.CharField(default='C', max_length=1, verbose_name='Perfil')),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'Usuario',
            },
            managers=[
                ('objects', contas.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': False,
                'db_table': 'aluno',
            },
            bases=('contas.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('contas.usuario',),
        ),
    ]
